### ISSUE TITLE
Cannot filter on inconsistent keys

### ISSUE THREAD

**Issue by PackeTsar** [PackeTsar/meraki-cli#10]
Some Meraki API endpoints return inconsistent keys in their data. An example of this is the `switch getDeviceSwitchPortsStatuses` command/function which will return `lldp` keys and values for a port only when data exists to populate the value. Example below:

```
~/$ meraki -j -f lldp:test switch getDeviceSwitchPortsStatuses --serial XXXX-XXXX-XXXX
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/meraki", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/meraki_cli/__main__.py", line 1188, in main
    result = _object_filter(result, args.filters,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/meraki_cli/__main__.py", line 709, in _object_filter
    if re.search(fdict['regex'], str(item[fdict['key']])):
KeyError: 'lldp'
~/$ 
```

This makes filtering based on those inconsistent keys impossible because the `_object_filter()` function will throw a KeyError when it attempts to filter a dict which doesn't contain the key. This is, up to this point, intended behavior. In fact there is even a test case for it (`testObjectFilterKeyMissingError()`).

This behavior needs to be changed to allow inconsistent, or even nonexistent keys to be provided for filtering. It is, however, not preferred to silently fail as that would prevent the user from being alerted of a mistake.

Below is a proposed NEW way to handle this within the `_object_filter()` function:

---

**If working under the default "OR" logic:**

- Loop through each filter key
    - Perform a check of all dicts in the `listofdicts` for the filter key
        - If the key exists in even a single dict, then escape the check and allow the next key to be checked
        - If the key does NOT exist in any of the dicts, then throw a warning and allow the next key to be checked (do not return from the filter, since we are using OR logic, and the next filter might allow objects to pass)
- Perform the filtering of the objects
    - If the object is missing a filter key, then fail only that filter. If the key exists filter as normal

---

**If working under the "AND" logic:**

- Loop through each filter key
    - Perform a check of all dicts in the `listofdicts` for the filter key
        - If the key exists in even a single dict, then escape the check and allow the next key to be checked
        - If the key does NOT exist in any of the dicts, then throw a warning and return an empty result (since none of the objects will be able to pass through the filter)
            - REASONING: It is better to return an empty result (to be safe) than return everything. If somebody fat fingers a filter key and pipes it into another command, and we default to returning everything, the results could be disastrous
- Perform the filtering of the objects
    - If the object is missing a filter key, then filter out that object. If the key exists filter as normal

**Comment by PackeTsar** [comment]
Fixed in v1.3.7
