### ISSUE TITLE
Meraki CLI appliance VLAN creation issue

### ISSUE THREAD

**Issue by pwellion4000** [PackeTsar/meraki-cli#23]
Hi There

I'm Trying to update/create a VLAN on an MX appliance via the Meraki CLI using of an existing Network containing an MX68:
For reference the MX68 is presently offline but all devices are part of a Meraki Network with vlaid licenses etc. I have sucessfully connected and updated basic parameters on devices such as the name

Version below:
linux-user-GLNBV04:~$ meraki --version
Meraki-CLI v1.5.0 | Meraki API Library v1.50.0 | Python 3.10.12

I'm attempting to add a vlan to the MX68 as per below

https://github.com/PackeTsar/meraki-cli/blob/master/COMMAND_GUIDE.md#appliance-update-network-appliance-vlans-settings. I have connected via API and can view organizations/networks etc. I have applied the below command whereby "network-id" is the relevant value for my specific network.

linux-user-GLNBV04:~$ meraki -ddd appliance updateNetworkApplianceVlan --networkId network-id --vlanId 166 --name v166 --subnet 192.168.166.0/24 --applianceIp 192.168.166.1

Debug shows:

linux-user-GLNBV04:~$ meraki -ddd appliance updateNetworkApplianceVlan --networkId network-id --vlanId 166 --name v166 --subnet 192.168.166.0/24 --applianceIp 192.168.166.1
2024-09-23 20:31:12,203 [DEBUG]  Argument Settings: 
{
    "apiKey": null,
    "debug": 3,
    "logfile": null,
    "configFile": null,
    "jsonOutput": false,
    "columns": null,
    "filters": null,
    "and_logic": false,
    "translations": null,
    "output_commands": false,
    "type": "appliance",
    "command": "updateNetworkApplianceVlan",
    "networkId": "network-id",
    "vlanId": "166",
    "kwargs": null
}
2024-09-23 20:31:12,203 [DEBUG]  Instantiating Meraki API with environment API key
2024-09-23 20:31:12,204 [INFO ]  Target method is <bound method Appliance.updateNetworkApplianceVlan of <meraki.api.appliance.Appliance object at 0x7f6205ee7d00>>
2024-09-23 20:31:12,204 [INFO ]  No STDIN detected. No pipe behind this instance.
2024-09-23 20:31:12,204 [DEBUG]  Cleaned Arguments: {'networkId': 'network-id', 'vlanId': '166'}
2024-09-23 20:31:12,204 [INFO ]  Calling target method with:
2024-09-23 20:31:12,204 [INFO ]      *Positionals: ['network-id', '166']
2024-09-23 20:31:12,204 [INFO ]      **Named/Kwargs: {'name': 'v166', 'subnet': '192.168.166.0/24', 'applianceIp': '192.168.166.1'}
2024-09-23 20:31:12,204 [DEBUG]  {'tags': ['appliance', 'configure', 'vlans'], 'operation': 'updateNetworkApplianceVlan', 'method': 'PUT', 'url': '/networks/network-id/appliance/vlans/166', 'json': {'name': 'v166', 'subnet': '192.168.166.0/24', 'applianceIp': '192.168.166.1'}}
2024-09-23 20:31:12,204 [INFO ]  PUT https://api.meraki.com/api/v1/networks/network-id/appliance/vlans/166
2024-09-23 20:31:12,356 [ERROR]  appliance, updateNetworkApplianceVlan - 404 Not Found, b''
2024-09-23 20:31:12,356 [CRITI]  An error occured in command execution, enable debugging to see more detail
2024-09-23 20:31:12,356 [CRITI]  An exception was thrown and is logged below
2024-09-23 20:31:12,356 [ERROR]  appliance, updateNetworkApplianceVlan - 404 Not Found, please wait a minute if the key or org was just newly created.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/meraki_cli/__main__.py", line 1314, in main
    result = arg_obj.method(*positionals, **arg_dict)
  File "/usr/local/lib/python3.10/dist-packages/meraki/api/appliance.py", line 2174, in updateNetworkApplianceVlan
    return self._session.put(metadata, resource, payload)
  File "/usr/local/lib/python3.10/dist-packages/meraki/rest_session.py", line 490, in put
    response = self.request(metadata, 'PUT', url, json=json)
  File "/usr/local/lib/python3.10/dist-packages/meraki/rest_session.py", line 301, in request
    raise APIError(metadata, response)
meraki.exceptions.APIError: appliance, updateNetworkApplianceVlan - 404 Not Found, please wait a minute if the key or org was just newly created.

Any idea of the potential issue? Much appreciated.
linux-user-GLNBV04:~$ 

Unsure as to why this CLI command is not working

**Comment by PackeTsar** [comment]
Are you able to get the current details of VLAN 166 with this? `meraki -ddd appliance getNetworkApplianceVlan --networkId network-id --vlanId 166`. In order to update it, it needs to already exist. Otherwise you would need to `meraki appliance createNetworkApplianceVlan`

**Comment by pwellion4000** [comment]
Ahh my bad that will do it. Thanks for such a prompt reply really appreciate your fantastic work on this, will make my life so much easier. More reading to be done on my side

Thanks

**Comment by PackeTsar** [comment]
@pwellion4000 no problem at all. I'm glad that fixed the issue!
