### ISSUE TITLE
Positional arguments don't decode JSON

### ISSUE THREAD

**Issue by PackeTsar** [PackeTsar/meraki-cli#9]
If a positional (required) argument with a list or dict annotation type is passed into Meraki-CLI, and that value is of proper JSON format, it is not decoded into a native dict/list, but it should be.

If the argument comes from a keyword arg in the source method, this decode happens fine.

**Comment by PackeTsar** [comment]
<img width="1766" alt="IMG_6303" src="https://user-images.githubusercontent.com/16087223/132794932-a6fa5126-bb79-4402-80b9-35a22adcb299.png">

**Comment by PackeTsar** [comment]
<img width="1764" alt="IMG_5501" src="https://user-images.githubusercontent.com/16087223/132794948-4cec7ec5-7458-4bc4-a90c-d3297c65545d.png">

**Comment by PackeTsar** [comment]
Fixed in v1.3.5. Closing

**Comment by PackeTsar** [comment]
Issue possibly still happening. Reopened

**Comment by mikevoelker** [comment]
new loan #17721936

old loan #af106847




C:\Users\XXXXXXXXXXX>meraki -ddd switch createNetworkSwitchStack --networkId L_722827740192968139 --name 6107-SWI-COR --serials '["Q2QW-XF82-APPF", "Q2QW-XMZQ-EVVQ"]'
2021-09-10 10:17:59,069 [DEBUG]  Argument Settings:
{
    "apiKey": null,
    "debug": 3,
    "logfile": null,
    "configFile": null,
    "jsonOutput": false,
    "columns": null,
    "filters": null,
    "and_logic": false,
    "translations": null,
    "output_commands": false,
    "type": "switch",
    "command": "createNetworkSwitchStack",
    "networkId": "L_722827740192968139",
    "name": "6107-SWI-COR",
    "serials": [
        "'[Q2QW-XF82-APPF,"
    ]
}
2021-09-10 10:17:59,069 [DEBUG]  Instantiating Meraki API with environment API key
2021-09-10 10:17:59,079 [INFO ]  Target method is <bound method Switch.createNetworkSwitchStack of <meraki.api.switch.Switch object at 0x000001BF05C895B0>>
2021-09-10 10:17:59,079 [INFO ]  No STDIN detected. No pipe behind this instance.
2021-09-10 10:17:59,081 [DEBUG]  Cleaned Arguments: {'networkId': 'L_722827740192968139', 'name': '6107-SWI-COR', 'serials': ["'[Q2QW-XF82-APPF,"]}
2021-09-10 10:17:59,082 [INFO ]  Calling target method with:
2021-09-10 10:17:59,083 [INFO ]      *Positionals: ['L_722827740192968139', '6107-SWI-COR', ["'[Q2QW-XF82-APPF,"]]
2021-09-10 10:17:59,084 [INFO ]      **Named/Kwargs: {}
2021-09-10 10:17:59,084 [DEBUG]  {'tags': ['switch', 'configure', 'stacks'], 'operation': 'createNetworkSwitchStack', 'method': 'POST', 'url': '/networks/L_722827740192968139/switch/stacks', 'json': {'name': '6107-SWI-COR', 'serials': ["'[Q2QW-XF82-APPF,"]}}
2021-09-10 10:17:59,085 [INFO ]  POST https://api.meraki.com/api/v1/networks/L_722827740192968139/switch/stacks
2021-09-10 10:17:59,940 [ERROR]  switch, createNetworkSwitchStack - 400 Bad Request, b' '
2021-09-10 10:17:59,941 [CRITI]  An error occured in command execution, enable debugging to see more detail
2021-09-10 10:17:59,951 [WARNI]  An exception was thrown and is logged below
2021-09-10 10:17:59,952 [ERROR]  switch, createNetworkSwitchStack - 400 Bad Request,
Traceback (most recent call last):
  File "C:\Users\XXXXXXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\meraki_cli\__main__.py", line 1173, in main
    result = arg_obj.method(*positionals, **arg_dict)
  File "C:\Users\XXXXXXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\meraki\api\switch.py", line 1517, in createNetworkSwitchStack
    return self._session.post(metadata, resource, payload)
  File "C:\Users\XXXXXXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\meraki\rest_session.py", line 447, in post
    response = self.request(metadata, 'POST', url, json=json)
  File "C:\Users\XXXXXXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\meraki\rest_session.py", line 278, in request
    raise APIError(metadata, response)
meraki.exceptions.APIError: switch, createNetworkSwitchStack - 400 Bad Request,

**Comment by PackeTsar** [comment]
Was fixed in v1.3.5
